/**
  ******************************************************************************
  * File Name          : gpio.h
  * Author             : (partially) auto-generated by STM32CubeIDE
  * Author             : Philipp v. K. <philipp.van-kempen@tum.de>
  * Description        : This file contains all the functions prototypes for
  *                      the gpio
  ******************************************************************************
  * @attention
  *
  * [Copyright (c) 2020 STMicroelectronics]
  *
  * Modifications by @PhilippvK:
  * - Changed formatting according to cpplint
  * - Clean up everything except USER-button
  *
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef SRC_GPIO_H_
#define SRC_GPIO_H_
#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "main.h"

void MX_GPIO_Init(void);

#ifdef __cplusplus
}
#endif
#endif  // SRC_GPIO_H_
